version: 0.2

phases:
  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh push-to-ecr.sh# make files executable
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - echo build started on `date`
      - echo Building and Pushing docker build image
      - ./push-to-ecr.sh
      - ./apply-terraform.sh
      - echo Writing image definitions file...
      - printf '[{"name":"hirodaridevdock/angular","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json